---

  - name: "update packages"
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "install node and npm"
    become: yes
    apt:
      name: ['npm', 'nodejs']
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      production: yes
      global: yes
      state: present