---


  - name: "move the backend binaries to server"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/backend
      recursive: true


  - name: "move application dependencies"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/backend
      recursive: true


  - name: "stop existing apps"
    become: true
    command: |
      pm2 stop all
      pm2 delete all
    ignore_errors: true


  - name: "start server"
    become: true
    command: |
      pm2 start main.js
    args:
      chdir: /home/ubuntu/backend/dist
    environment:
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
      - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
      - TYPEORM_PORT: 5432
      - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
      - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
      - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
      - TYPEORM_MIGRATIONS_DIR: "./migrations"
      - TYPEORM_MIGRATIONS: "./migrations/*.js"
      - TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
