---


  - name: "move the backend binaries to server"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/backend
      recursive: true


  - name: "move application dependencies"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/backend
      recursive: true


  - name: "stop existing apps"
    become: true
    command: |
      pm2 stop default
      pm2 delete all
    ignore_errors: true


  - name: "start server"
    become: true
    command: |
      pm2 start main.js
    args:
      chdir: /home/ubuntu/backend/dist
